### ISSUE TITLE
Extracting archivePHP Fatal error at version 0.1.4

### ISSUE THREAD

**Issue by hanovruslan** [neronmoon/scriptsdev#11]
composer version 1.8.4 and some prior to this one

stack trace

```bash
 - Installing neronmoon/scriptsdev (v0.1.4): Loading from cache
 Extracting archivePHP Fatal error:  Uncaught TypeError: Argument 1 passed to ScriptsDev\PackageScriptsExtractor::extract() must be an instance of Composer\Package\Package, instance of Composer\Package\RootAliasPackage given, called in ... vendor/neronmoon/scriptsdev/src/Plugin.php on line 24 and defined in ... vendor/neronmoon/scriptsdev/src/PackageScriptsExtractor.php:29
Stack trace:
#0 vendor/neronmoon/scriptsdev/src/Plugin.php(24): ScriptsDev\PackageScriptsExtractor->extract(Object(Composer\Package\RootAliasPackage))
#1 composer.phar/src/Composer/Plugin/PluginManager.php(236): ScriptsDev\Plugin->activate(Object(Composer\Composer), Object(Composer\IO\ConsoleIO))
#2 composer.phar/src/Composer/Plugin/PluginManager.php(205): Composer\Plugin\PluginManager->addPlugin(Object(ScriptsDev\Plugin))
#3 composer.phar/src/Compo in vendor/neronmoon/scriptsdev/src/PackageScriptsExtractor.php on line 29

Fatal error: Uncaught TypeError: Argument 1 passed to ScriptsDev\PackageScriptsExtractor::extract() must be an instance of Composer\Package\Package, instance of Composer\Package\RootAliasPackage given, called in vendor/neronmoon/scriptsdev/src/Plugin.php on line 24 and defined in vendor/neronmoon/scriptsdev/src/PackageScriptsExtractor.php:29
Stack trace:
#0 vendor/neronmoon/scriptsdev/src/Plugin.php(24): ScriptsDev\PackageScriptsExtractor->extract(Object(Composer\Package\RootAliasPackage))
#1 composer.phar/src/Composer/Plugin/PluginManager.php(236): ScriptsDev\Plugin->activate(Object(Composer\Composer), Object(Composer\IO\ConsoleIO))
#2 composer.phar/src/Composer/Plugin/PluginManager.php(205): Composer\Plugin\PluginManager->addPlugin(Object(ScriptsDev\Plugin))
#3 composer.phar/src/Compo in vendor/neronmoon/scriptsdev/src/PackageScriptsExtractor.php on line 29

```

version 0.1.3 is OK

also updating from 0.1.3 to 0.1.4 is OK

**Comment by neronmoon** [comment]
Thanks for reporting! Will be fixed in 0.1.5
